### PR TITLE
Feature/id 11/upcoming event section

### PR DESCRIPTION
**Pull request by CatCoder36**
As a user I would like to see a section that allows me to see upcoming events:

**Acceptance criteria:** 
- You must be able to observe a loading sekelton representing that the values are loading.
- An event not found sign must be displayed in case there is no upcoming event.
- 6 event cards must be displayed in case several events are found or the number of events found must be less than 6.

ClickUp: https://app.clickup.com/t/868abvvvv

Review:
@victor-fundacion 
@gabitrujillo

### CODE REVIEW

**Review by gabitrujillo — APPROVED** [review]

**Review by victor-fundacion — CHANGES_REQUESTED** [review]
The events never load.
500 server when loading home page.
Event service api was  up and .env configured, still the error persists.
image

**Comment by CatCoder36** [comment]
> The events never load. 500 server when loading home page. Event service api was up and .env configured, still the error persists. image

I suggest you run npm install and test your event backend locally before running the tests, I also suggest you verify that you have events registered in your database.

**Comment by victor-fundacion** [comment]
> > The events never load. 500 server when loading home page. Event service api was up and .env configured, still the error persists. image
> 
> I suggest you run npm install and test your event backend locally before running the tests, I also suggest you verify that you have events registered in your database.

Thanks for the suggestion, but all were applied before commenting the error, still, the events do not show on home page.
@CatCoder36

**Review by victor-fundacion — CHANGES_REQUESTED** [review]
Integrate your feature to recieve events from the api gateway.

**Review by victor-fundacion — APPROVED** [review]
Events working. Good.
image

**Pull request merged**
