### PR TITLE
Feature/id 27/update events

### PR DESCRIPTION
**Pull request by JP-Arequipa**
# Reviewers:
@Elvis-Castro-H  @CatCoder36

### CODE REVIEW

**Review by Elvis-Castro-H — CHANGES_REQUESTED** [review]
There is a security gap when making update requests by any user, since any user (with access to the API) could modify events from any other user.
Change the base branch to Develop

**Comment by CatCoder36** [comment]
[Grabación de pantalla desde 20-06-24 22:30:31.webm](https://github.com/user-attachments/assets/d665f2c4-43af-44c6-807d-7d3d8d3f0064)

**Comment by CatCoder36** [comment]
Check the functionality: 
https://jalafoundation-my.sharepoint.com/:v:/g/personal/mauricio_mamani_fundacion-jala_org/EV70i_kZ_B5Is_8Vjsbj6JoBewAfT61XFO7JrmT2QLeyDw?e=AArIll&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D

**Review by CatCoder36 — APPROVED** [review]

**Review by Elvis-Castro-H — APPROVED** [review]
Good job

**Pull request merged**
